### ISSUE TITLE
'Logo' of EnergyMixer on front-page should be CSS-solution, no mark-up image

### ISSUE THREAD

**Issue by dennisquintel** [quintel/energymixer#115]
instead of

``` html
<section id="intro_text">
  <img src="/images/layout/energy_mixer_header.png?1316442778" alt="Energy_mixer_header">
```

something like:

``` html
<section id="intro_text">
  <h1>Energy Mixer</h1>
```

with

``` css
h1{
  background-image: url("foo") no-repeat top left
}
```
