### ISSUE TITLE
Replace closing img in markup with background-image

### ISSUE THREAD

**Issue by dennisquintel** [quintel/energymixer#129]
instead of:

``` html
<a class="close_popup" href="#">
  <img src="/images/icons/close.png?1316783506" alt="Close">
</a>
```

we need this:

``` html
<a class="close_popup" href="#">
  close
</a>
```

``` css
a{
  text-indent: -9999px;
  background: url("images/icon/close.png) center center no-repeat;
}
```
